In [13]:
import pandas as pd
import numpy as np

# Part 1

## Loading the Datset

Importing the csv into the project as a DataFrame

In [14]:
df = pd.read_csv("sample-data/california_housing_train.csv")

In [15]:
print(df)

       longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -114.31     34.19                15.0       5612.0          1283.0   
1        -114.47     34.40                19.0       7650.0          1901.0   
2        -114.56     33.69                17.0        720.0           174.0   
3        -114.57     33.64                14.0       1501.0           337.0   
4        -114.57     33.57                20.0       1454.0           326.0   
...          ...       ...                 ...          ...             ...   
16995    -124.26     40.58                52.0       2217.0           394.0   
16996    -124.27     40.69                36.0       2349.0           528.0   
16997    -124.30     41.84                17.0       2677.0           531.0   
16998    -124.30     41.80                19.0       2672.0           552.0   
16999    -124.35     40.54                52.0       1820.0           300.0   

       population  households  median_income  media

Printing the first 5 and last 10 rows of the DataFrame

In [16]:
df2 = pd.DataFrame()
df2 = pd.concat([df.head(5),df.tail(10)],ignore_index=False)
print(df2)

       longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -114.31     34.19                15.0       5612.0          1283.0   
1        -114.47     34.40                19.0       7650.0          1901.0   
2        -114.56     33.69                17.0        720.0           174.0   
3        -114.57     33.64                14.0       1501.0           337.0   
4        -114.57     33.57                20.0       1454.0           326.0   
16990    -124.22     41.73                28.0       3003.0           699.0   
16991    -124.23     41.75                11.0       3159.0           616.0   
16992    -124.23     40.81                52.0       1112.0           209.0   
16993    -124.23     40.54                52.0       2694.0           453.0   
16994    -124.25     40.28                32.0       1430.0           419.0   
16995    -124.26     40.58                52.0       2217.0           394.0   
16996    -124.27     40.69                36.0      

## Data Summary

Using describe to give an analysis of all the numerical columns

In [17]:
df.describe()

longitude      latitude  housing_median_age   total_rooms  \
count  17000.000000  17000.000000        17000.000000  17000.000000   
mean    -119.562108     35.625225           28.589353   2643.664412   
std        2.005166      2.137340           12.586937   2179.947071   
min     -124.350000     32.540000            1.000000      2.000000   
25%     -121.790000     33.930000           18.000000   1462.000000   
50%     -118.490000     34.250000           29.000000   2127.000000   
75%     -118.000000     37.720000           37.000000   3151.250000   
max     -114.310000     41.950000           52.000000  37937.000000   

       total_bedrooms    population    households  median_income  \
count    17000.000000  17000.000000  17000.000000   17000.000000   
mean       539.410824   1429.573941    501.221941       3.883578   
std        421.499452   1147.852959    384.520841       1.908157   
min          1.000000      3.000000      1.000000       0.499900   
25%        297.000000    790.000000    282.000000       2.566375   
50%        434.000000   1167.000000    409.000000       3.544600   
75%        648.250000   1721.000000    605.250000       4.767000   
max       6445.000000  35682.000000   6082.000000      15.000100   

       median_house_value  
count        17000.000000  
mean        207300.912353  
std         115983.764387  
min          14999.000000  
25%         119400.000000  
50%         180400.000000  
75%         265000.000000  
max         500001.000000

Finding the unique values in the total_bedroom column using the unique() method of DataFrame objects.
Then using the size attribute of the numpy array returned from the unique method to find the number of unique values

In [18]:
print(df.total_bedrooms.unique())
print(df.total_bedrooms.unique().size)

[1283. 1901.  174. ... 1637. 1308.  936.]
1848


## Data Transformation

Creating a new column called total_bedrooms_per_total_rooms

In [19]:
df['total_bedrooms_per_total_rooms'] = df['total_bedrooms']/df['total_rooms']
print(df)

       longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -114.31     34.19                15.0       5612.0          1283.0   
1        -114.47     34.40                19.0       7650.0          1901.0   
2        -114.56     33.69                17.0        720.0           174.0   
3        -114.57     33.64                14.0       1501.0           337.0   
4        -114.57     33.57                20.0       1454.0           326.0   
...          ...       ...                 ...          ...             ...   
16995    -124.26     40.58                52.0       2217.0           394.0   
16996    -124.27     40.69                36.0       2349.0           528.0   
16997    -124.30     41.84                17.0       2677.0           531.0   
16998    -124.30     41.80                19.0       2672.0           552.0   
16999    -124.35     40.54                52.0       1820.0           300.0   

       population  households  median_income  media

Finding the mean and the standard deviation of the newly made column

In [20]:
print('the mean of the new column is:',df['total_bedrooms_per_total_rooms'].mean())
print('the standard deviation of the new column is:',df['total_bedrooms_per_total_rooms'].std())

the mean of the new column is: 0.21275998821034803
the standard deviation of the new column is: 0.05782300890316167


## Data Filtering

Filtering the dataset based on the single condition on median_income

In [21]:
print(df[df['median_income']>5])

       longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
32       -115.39     32.76                16.0       1136.0           196.0   
69       -115.55     32.98                33.0       2266.0           365.0   
92       -115.57     32.78                20.0       1534.0           235.0   
98       -115.58     32.78                 5.0       2494.0           414.0   
100      -115.59     32.79                 8.0       2183.0           307.0   
...          ...       ...                 ...          ...             ...   
16737    -122.89     38.38                16.0       2017.0           369.0   
16762    -122.94     38.57                33.0       1530.0           266.0   
16776    -123.00     38.33                 8.0       3223.0           637.0   
16802    -123.17     39.18                14.0       2240.0           327.0   
16899    -124.05     40.94                14.0       1452.0           217.0   

       population  households  median_income  media

Creating a subset based on two conditions on the original dataset

In [22]:
df2 = df[(df['total_rooms']>10000) & (df['median_house_value']<150000)]
print(df2)

       longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
133      -116.06     34.15                15.0      10377.0          2331.0   
191      -116.36     33.88                11.0      12557.0          3098.0   
198      -116.38     33.73                10.0      11836.0          2405.0   
201      -116.39     33.82                15.0      11115.0          2257.0   
229      -116.47     33.81                 7.0      10105.0          2481.0   
...          ...       ...                 ...          ...             ...   
12654    -121.75     38.67                 9.0      12139.0          2640.0   
12772    -121.79     36.64                11.0      32627.0          6445.0   
13388    -121.94     38.27                35.0      10869.0          2226.0   
13707    -122.00     38.25                 7.0      11768.0          1893.0   
15436    -122.31     40.55                11.0      13714.0          2302.0   

       population  households  median_income  media

## Exporting Modified Data

Exporting the modified DataFrame as a CSV file. Saved in the sample_data folder

In [23]:
df.to_csv('sample-data/newhousingdata.csv')

# Part 2

## Array Creation and Indexing

Using np.arange to generate ndarray of integers from 1 to 20

In [24]:
arr = np.arange(1,21)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


Using slicing to get the even numbers

In [25]:
print(arr[1::2])

[ 2  4  6  8 10 12 14 16 18 20]


Creating an empty (5,4) array with the random.randint method

In [26]:
arr1 = np.random.randint(10,100,(5,4),dtype = int)
print(arr1)

[[35 97 25 49]
 [39 75 84 95]
 [36 22 80 22]
 [40 78 23 76]
 [87 47 18 96]]


Using slicing to get the required subset of the 5x4 array

In [27]:
arr2 = arr1[0:3,0:2]
print(arr2)

[[35 97]
 [39 75]
 [36 22]]


## Array Manipulation

Using the numpy.reshape() method to reshape the earlier 1d array to a 2d array

In [28]:
arr = np.reshape(arr,(4,5))
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


Using the above method to do the reverse

In [29]:
arr3 = np.reshape(arr1,(arr1.size))
print(arr3)

[35 97 25 49 39 75 84 95 36 22 80 22 40 78 23 76 87 47 18 96]


Using the numpy.matmul() method to muliply 2 matrices(2d arrays)

In [30]:
arr4 = np.random.randint(10,100,(4,5))

arr5  = np.matmul(arr1,arr4)
print(arr5)

[[13289  5362 12326  8444 12248]
 [22469  8014 15837 13143 18860]
 [12564  5104  5996  6542  9118]
 [15202  5358 13257 10069 13786]
 [18122  5883 13840 13182 15443]]


## Boolean and Fancy Indexing

Creating an array of 50 random integers
Then using boolean indexing to obtain elements greater than 50.
Then using fancy indexing to get specific indices from the array

In [31]:
arr6 = np.random.randint(0,100,50)
print(arr6)
print(arr6[arr6>50])
print(arr6[[1,3,4,5,6]])

[ 2 74 15 77 74 13 37 19 56  1 34 43 66 73  1 47 34 87 22 46 19 94 22 87
 60 81 75 63 21 97 57 98 69 11 31  8 79 74 81 17 55 21 42 59 16 94 32 25
 97 32]
[74 77 74 56 66 73 87 94 87 60 81 75 63 97 57 98 69 79 74 81 55 59 94 97]
[74 77 74 13 37]


## Statistical Operations

Finding mean, max and the sum for each column using the respective method

In [32]:
x=np.mean(arr1,axis = 0)
print('The mean for each column is: ',x)
print('The max value for each column is: ',np.max(arr1,axis = 0))
print('The sum for each column is: ',np.sum(arr1,axis = 0))

The mean for each column is:  [47.4 63.8 46.  67.6]
The max value for each column is:  [87 97 84 96]
The sum for each column is:  [237 319 230 338]


Creating a mask and then applying that mask to arr1

In [33]:
mask = arr1>x
print(arr1[mask])

[97 75 84 95 80 78 76 87 96]


# Part 3

## Loops and Conditional statements

Fibbonacci series using while loop and using the old value of a to add to the current value of a to get the new value for the fibbonacci series

In [34]:
a = 0
b = 1
while(a<=100):
  print(a)
  temp = a
  a += b
  if(temp!=0):
    b = temp

0
1
2
3
5
8
13
21
34
55
89


FizzBuzz by manipulating the end parameter of the print function

In [35]:

for i in range(1,51):
  c=0
  if(i%3==0):
    print('Fizz',end = '')
    c=1
  if(i%5==0):
    print('Buzz',end='' )
    c=1
  if(c==0):
    print(i)
  else:
    print()

1
2
Fizz
4
Buzz
Fizz
7
8
Fizz
Buzz
11
Fizz
13
14
FizzBuzz
16
17
Fizz
19
Buzz
Fizz
22
23
Fizz
Buzz
26
Fizz
28
29
FizzBuzz
31
32
Fizz
34
Buzz
Fizz
37
38
Fizz
Buzz
41
Fizz
43
44
FizzBuzz
46
47
Fizz
49
Buzz


## Variable-Length Arguments

First taking input as a string and then splitting it to form a list of characters. Converting it all into integers using a for loop. Using the numpy method, median(), to get the median

In [36]:
str = input("Enter numbers seperated by spaces: ")
l = str.split()
for x in l:
  l[l.index(x)] = int(x)
u = np.median(l)
print("The median is: ", u)

The median is:  2.5


First taking the number of numbers from the user. Then using a for loop to get each of the numbers. Using the numpy method, mean(), to get the mean

In [37]:
n = int(input("enter number of numbers "))
l=[]
for i in range(0 ,n):
  l.append(int(input("enter number: ")))
print(np.mean(l))

2.0


## Error Handling

The try block is executed first. If an exception is encountered then the except block is executed from that point on in stead of the rest of the try block

In [38]:
try:
  n = int(input("Enter a number: "))
  print(100/n)
except:
  print("cannot divide by zero")

33.333333333333336


# Part 4

Creating a 3d array from the randint function of numpy.random

In [39]:
threeDarr = np.random.randint(1,100,(3,3,3))
print(threeDarr)

[[[93 22 27]
  [47 65 92]
  [77 69 64]]

 [[68 58 11]
  [37 40 55]
  [76 23 85]]

 [[58 30 32]
  [37 26 38]
  [90 85 19]]]


Swapping 2 axes of the 3d array

In [40]:
thrDarr = threeDarr.swapaxes(0,1)
print(thrDarr)

[[[93 22 27]
  [68 58 11]
  [58 30 32]]

 [[47 65 92]
  [37 40 55]
  [37 26 38]]

 [[77 69 64]
  [76 23 85]
  [90 85 19]]]


Finding sum along one of the axes.
For element theDarr[a][b][c]
1.   Axis 0 means it finds sum of all elements by changing a first before b and c
2.   Axis 1 means it finds sum of all elements by changing b first before c and c
3.   Axis 2 means it finds sum of all elements by changing c first before a and b




In [41]:
print(thrDarr.sum(axis = 0))

[[217 156 183]
 [181 121 151]
 [185 141  89]]


Adding a vector to each row of the arr1 matrix created in part 2 by broadcasting it

In [42]:
l = np.random.randint(0,100,4)
print(l+arr1)

[[ 76 169  27 148]
 [ 80 147  86 194]
 [ 77  94  82 121]
 [ 81 150  25 175]
 [128 119  20 195]]
